apiVersion: v1
kind: Service
metadata:
  name: acrservice
  labels:
    name: acrservice
    app: acrservice
spec:
  selector:
    name: helloworld 
  type: LoadBalancer
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP