apiVersion: "v1"
kind: Pod
metadata:
  name: helloworld
  labels:
    name: helloworld
spec:
  containers:
    - name: blue
      image: mbrandl.azurecr.io/phoenixautohelloworld:cb3
      ports:
        - containerPort: 80
          protocol: TCP 