apiVersion: v1
kind: Service
metadata:
  name: calcbackendsvc
  labels:
    name: calcbackendsvc
    app: calculator 
spec:
  ports:
  - port: 80
    name: calcbackend
    targetPort: 80
  selector:
    role: calcbackend
    app: calculator
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calcbackenddepl
spec:
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: jscalcbackend
        role: calcbackend
        app: calculator
    spec:
      containers:
      - name: calcbackend
        image: mbrandl.azurecr.io/calcbackend:latest
        imagePullPolicy: Always 
        ports:
          - containerPort: 80
            name: http         
            protocol: TCP