apiVersion: "v1"
kind: Pod
metadata:
  name: calcfrontend
  labels:
    name: calcfrontend
    app: calculator
spec:
  containers:
    - name: calcfrontend
      image: mbrandl.azurecr.io/calcfrontend:latest
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      env:
        - name: "ENDPOINT"
          value: "calcbackendsvc"
        - name: "INSTRUMENTATIONKEY"
          valueFrom:
            secretKeyRef:
              name: appinsightsecret
              key: appinsightkey