apiVersion: v1
kind: ReplicationController
metadata:
  name: calcfrontend
  labels:
    name: calcfrontend
    app: calculator
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: calcfrontend
    spec:
        containers:
          - name: calcfrontend
            image: mbrandl.azurecr.io/calcfrontend:latest
            ports:
              - containerPort: 80
                name: http
                protocol: TCP